import 'package:ancient_excavations_app/models/level_model.dart';

class MatchPairsLevelsRepository {
  final List<LevelModel> _simpleLevels = [
    LevelModel(
      difficult: LevelDifficult.simple,
      number: 1,
      isDone: false,
      minutes: 3,
      seconds: 0,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.simple,
      number: 2,
      isDone: false,
      minutes: 3,
      seconds: 0,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.simple,
      number: 3,
      isDone: false,
      minutes: 3,
      seconds: 0,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.simple,
      number: 4,
      isDone: false,
      minutes: 3,
      seconds: 0,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.simple,
      number: 5,
      isDone: false,
      minutes: 3,
      seconds: 0,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.simple,
      number: 6,
      isDone: false,
      minutes: 3,
      seconds: 0,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.simple,
      number: 7,
      isDone: false,
      minutes: 3,
      seconds: 0,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.simple,
      number: 8,
      isDone: false,
      minutes: 3,
      seconds: 0,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.simple,
      number: 9,
      isDone: false,
      minutes: 3,
      seconds: 0,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.simple,
      number: 10,
      isDone: false,
      minutes: 3,
      seconds: 0,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
  ];

  List<LevelModel> get getSimpleLevels => _simpleLevels;

  final List<LevelModel> _middleLevels = [
    LevelModel(
      difficult: LevelDifficult.middle,
      number: 1,
      isDone: false,
      minutes: 2,
      seconds: 30,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.middle,
      number: 2,
      isDone: false,
      minutes: 2,
      seconds: 30,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.middle,
      number: 3,
      isDone: false,
      minutes: 2,
      seconds: 30,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.middle,
      number: 4,
      isDone: false,
      minutes: 2,
      seconds: 30,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.middle,
      number: 5,
      isDone: false,
      minutes: 2,
      seconds: 30,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.middle,
      number: 6,
      isDone: false,
      minutes: 2,
      seconds: 30,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.middle,
      number: 7,
      isDone: false,
      minutes: 2,
      seconds: 30,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.middle,
      number: 8,
      isDone: false,
      minutes: 2,
      seconds: 30,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.middle,
      number: 9,
      isDone: false,
      minutes: 2,
      seconds: 30,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.middle,
      number: 10,
      isDone: false,
      minutes: 2,
      seconds: 30,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
  ];

  List<LevelModel> get getMiddleLevels => _middleLevels;

  final List<LevelModel> _advancedLevels = [
    LevelModel(
      difficult: LevelDifficult.advanced,
      number: 1,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.advanced,
      number: 2,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.advanced,
      number: 3,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.advanced,
      number: 4,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.advanced,
      number: 5,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.advanced,
      number: 6,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.advanced,
      number: 7,
      isDone: false,
      minutes: 1,
      seconds: 0,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.advanced,
      number: 8,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.advanced,
      number: 9,
      isDone: false,
      minutes: 1,
      seconds: 0,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
    LevelModel(
      difficult: LevelDifficult.advanced,
      number: 10,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/1.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/2.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/3.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/4.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/5.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/6.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/7.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/8.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/9.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/10.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/11.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/12.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/13.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/14.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/15.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/16.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/17.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/18.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/19.png',
        'assets/images/match_pairs/20.png',
        'assets/images/match_pairs/20.png',
      ],
    ),
  ];

  List<LevelModel> get getAdvancedLevels => _advancedLevels;

}