import 'package:ancient_excavations_app/models/level_model.dart';

class MinesweeperLevelsRepository {
  final List<LevelModel> _simpleLevels = [
    LevelModel(
      difficult: LevelDifficult.simple,
      number: 1,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.simple,
      number: 2,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.simple,
      number: 3,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.simple,
      number: 4,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.simple,
      number: 5,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.simple,
      number: 6,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.simple,
      number: 7,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.simple,
      number: 8,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.simple,
      number: 9,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.simple,
      number: 10,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
  ];

  List<LevelModel> get getSimpleLevels => _simpleLevels;

  final List<LevelModel> _middleLevels = [
    LevelModel(
      difficult: LevelDifficult.middle,
      number: 1,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.middle,
      number: 2,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.middle,
      number: 3,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.middle,
      number: 4,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.middle,
      number: 5,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.middle,
      number: 6,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.middle,
      number: 7,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.middle,
      number: 8,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.middle,
      number: 9,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.middle,
      number: 10,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
  ];

  List<LevelModel> get getMiddleLevels => _middleLevels;

  final List<LevelModel> _advancedLevels = [
    LevelModel(
      difficult: LevelDifficult.advanced,
      number: 1,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.advanced,
      number: 2,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.advanced,
      number: 3,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.advanced,
      number: 4,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.advanced,
      number: 5,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.advanced,
      number: 6,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.advanced,
      number: 7,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.advanced,
      number: 8,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.advanced,
      number: 9,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
    LevelModel(
      difficult: LevelDifficult.advanced,
      number: 10,
      isDone: false,
      minutes: 2,
      seconds: 0,
      cardImages: [
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/bomb.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',
        'assets/images/minesweeper/diamond.png',

      ],
    ),
  ];

  List<LevelModel> get getAdvancedLevels => _advancedLevels;
}